name: Auto Deploy API

on:
  push:
    paths:
    - 'TodoistProxyAPI/**'
    - '.github/workflows/auto-deploy-api.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download sources
      uses: actions/checkout@v1
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build with Maven
      run: mvn package --file TodoistProxyAPI/pom.xml
      env:
        TODOIST_CLIENT_ID: ${{ secrets.TODOIST_CLIENT_ID_PROD }}
        TODOIST_CLIENT_SECRET: ${{ secrets.TODOIST_CLIENT_SECRET_PROD }}
    
    - name: GCP / Install gcloud SDK
      run: |
        sudo apt-get update && sudo apt-get install google-cloud-sdk && sudo apt-get install google-cloud-sdk-app-engine-java
        
    - name: GCP / Activate Service Account 
      env: 
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH_ENV_TEST }}
      run: |
        echo "$GCLOUD_AUTH" | base64 --decode > "$HOME"/gcloud.json
        sh -c "gcloud auth activate-service-account --key-file=$HOME/gcloud.json $*"

    - name: GCP / Set Project
      env:
        CLOUDSDK_CORE_PROJECT: websitequickadding4todoisttest
      run: |
        gcloud config set project "$CLOUDSDK_CORE_PROJECT"
                     
    - name: GCP / Deploy App 
      run: |
        gcloud app deploy TodoistProxyAPI/target/TodoistQuickWebSiteURLAddAsTask-1.0-SNAPSHOT/WEB-INF/appengine-web.xml --quiet
